### ISSUE TITLE
DictBase的作用是什么?   空行如何删除?

### ISSUE THREAD

**Issue by feng99** [Nicole0724/sql-to-struct#1]
有2个问题  请教下

1.DictBase的作用是什么

2.我把注释放到 每一行的结尾后    行与行之间有了一个空行  如何删除呢  谢谢

CreateTime string `gorm:"create_time"` //添加时间

UpdateTime string `gorm:"update_time"` //更新时间

IsDelete int64 `gorm:"is_delete"` //是否删除 1:是:0否

**Comment by Nicole0724** [comment]
修改模板即可
`type {{.DB.TableName | ToBigCamelCase }}BaseTest struct{
{{- range .DB.Columns }}
{{- $isShowBaseLength := len .IsShowBase }}
{{- if eq $isShowBaseLength 0}}
{{- $typeLen := len .Type }} 
{{if gt $typeLen 0}}	{{.Name | ToBigCamelCase}}	{{.Type}} {{.Tag}} {{else}}	{{.Name}}{{end}} {{- $length := len .Comment }} {{if gt $length 0}}	//{{- .Comment }} {{- else}}	//{{- .Name}} {{end}}
{{- end}}
{{- end}}
}`

结果：
`
type DictBaseTest struct{ 
	Code	string `gorm:"code" form:"code" json:"code"`  	//字典码 
	DictKey	string `gorm:"dict_key" form:"dictKey" json:"dictKey"`  	//字典值 
	DictValue	string `gorm:"dict_value" form:"dictValue" json:"dictValue"`  	//字典名称 
	Id	int32 `gorm:"id" form:"id" json:"id"`  	//主键 
	IsSealed	int32 `gorm:"is_sealed" form:"isSealed" json:"isSealed"`  	//是否已封存 
	ParentId	int32 `gorm:"parent_id" form:"parentId" json:"parentId"`  	//父主键 
	Remark	string `gorm:"remark" form:"remark" json:"remark"`  	//字典备注 
	Sort	int32 `gorm:"sort" form:"sort" json:"sort"`  	//排序
}
`

![image](https://user-images.githubusercontent.com/10487328/201612588-bb75a28f-54a5-4774-8888-ad3fa0e99d46.png)

**Comment by Nicole0724** [comment]
1.DictBase的作用是什么

 去除了 一些常规字段  例如 创建时间 更新时间等等 具体过滤字段  在internal 下的 model -> mysql  中该变量进行控制 DBSkipColName

**Comment by Nicole0724** [comment]
/**
{{- 忽略前面的空
gt 大于
lt 小于
eq 等于
ne 不等于
*/

**Comment by feng99** [comment]
{{- if gt $typeLen 0}} {{ .Name | ToBigCamelCase}}
感谢    解决了.
