### ISSUE TITLE
如何在另一个项目的单元测试中使用这个项目呢?

### ISSUE THREAD

**Issue by feng99** [Nicole0724/sql-to-struct#2]
你好,如何在另一个的项目单元测试中使用这个项目呢?

**Comment by Nicole0724** [comment]
目前这个不支持 直接使用，你可以将里面的核心代码 放你项目中 写一个test 来调用即可  不过你这个是一个好需求  可以后面更新下

**Comment by feng99** [comment]
好哒, 期待您的更新.

**Comment by Nicole0724** [comment]
gitee 上处理了这个

仓库lib 地址：https://gitee.com/nicole-go-libs/sql-to-struct-lib
lib 使用demo：https://gitee.com/nicole-go-libs/sql-to-struct-lib-demo
