### ISSUE TITLE
如何批量生成指定表前缀的表呢?

### ISSUE THREAD

**Issue by feng99** [Nicole0724/sql-to-struct#3]
您好 当前有这个需求
有10个表   表前缀是一样的  比如  t_user_
如何一次性生成这个10个表呢?
我看当是前一次性生成全库所有表的.

**Comment by Nicole0724** [comment]
![image](https://user-images.githubusercontent.com/10487328/204191412-a1d7d783-ae7a-40d9-b43a-bff67652906e.png)
修改这个查询即可

**Comment by Nicole0724** [comment]
目前查询的是当前数据库下的所有表，你再添加一个 表名的模糊查询即可

**Comment by Nicole0724** [comment]
gitee 上处理了这个，最新解决方案如下：
通过mod 方式添加，然后走testing 方式来管理

仓库lib 地址：https://gitee.com/nicole-go-libs/sql-to-struct-lib
lib 使用demo：https://gitee.com/nicole-go-libs/sql-to-struct-lib-demo

**Comment by Nicole0724** [comment]
原有https://github.com/Nicole0724/sql-to-struct 项目，也新增了 该功能

通过在yaml 文件中的 likeTableName 来定义

**Comment by feng99** [comment]
收到   感谢您的更新.   我邀请朋友们来star

**Comment by Nicole0724** [comment]
> 收到 感谢您的更新. 我邀请朋友们来star

thanks
